apiVersion: v1
kind: Secret
metadata:
  name: cars-postgres-secret
type: Opaque
data:
  CARS_DB_USERNAME: Y2FyX3VzZXI=
  CARS_DB_PASSWORD: Y2FyX3Bhc3N3ZA==
  CARS_DB_DATABASE: Y2FyX2Ri
  MANUFACTURER_SERVICE_HOST_URL: 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars-postgres
  template:
    metadata:
      labels:
        app: cars-postgres
    spec:
      containers:
        - name: cars-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cars-postgres-secret
                  key: CARS_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cars-postgres-secret
                  key: CARS_DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cars-postgres-secret
                  key: CARS_DB_DATABASE

---
apiVersion: v1
kind: Service
metadata:
  name: cars-postgres-service
spec:
  selector:
    app: cars-postgres
  ports:
    - name: cars-postgres-service-port
      port: 5432
      targetPort: 5432